# Dim screen
listener {
  # Changing brightness to minimal after 5min.
  timeout = 300 
  on-timeout = brightnessctl -s set 10 
  on-resume = brightnessctl -r
}

# Locking screen
listener {
  # Locking screen after 10min.
  timeout = 600
  on-timeout = hyprlock
}

# Suspend
listener {
  # Suspending system after 30min.
  timeout = 1800
  on-timeout = systemctl suspend
}
